apply plugin: 'com.android.application'

android {
    compileSdkVersion 19
    namespace 'com.unisocsu.sudebug'
    defaultConfig {
        applicationId "com.unisocsu.sudebug"
        minSdkVersion 19
        targetSdkVersion 19
        versionCode 1
        versionName "1.0"
    }
}
dependencies {
    implementation 'com.android.support:appcompat-v7:19.1.0'
}
